---
title: "Gov 50 Final Project"
author: Brock Locnikar
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

Data =  Civil War Data provided in class


My research question is if greater than 1/3 export revenues from fuels is a causal factor in low polity scores (Polity Score:  Index of democratization). 

My hypothesis is that oil centralizes power structures and economies and this leads to the emergence of more autocratic governments with limited democratic institutions. The example often used for the petroleum producing curse is the Gulf region where despite high economic activity the region remains undemocratic. I believe that the effect oil has will be regional-agnostic and effect all regions of the world evenly. Meaning that all countries with greater than 1/3 export revenues from fuels will have lower polity scores than those that do not, especially within their own region. 


I will be measuring the polity scores for Eastern Europe, Asia, Latin America, Western Democracies/Japan, Sub Saharan Africa, and the Middle East and North Africa for both when greater than 1/3 export revenues come from fuels and when less than 1/3 export revenues come from fuels. Polity scores measure the level of democratization of a state and will be a useful measure on the impact of oil production on governmental structures.


If polity scores are higher for high oil producers in the same region than low fuel producers, than my hypothesis is incorrect that fuel production alone lowers democratization. If polity scores are lower for high fuel producers than low fuel producers, then my hypothesis may be correct, but I will still have to run further anlysis for confounding factors such as ongoing civil wars and GDP.



polity2 score vs oil > 1/3 revenues from oil
```{r}
library(ggplot2)
library(dplyr)
library(gapminder)
library(tidyverse)


civilwar <- read_csv("~/Downloads/civilwar.csv")

plot1<- civilwar|>
  mutate(OilGeography = case_when(
      Oil == 0 & eeurop == 1 ~ "E. Europe Low Oil",
      Oil == 1 & eeurop == 1 ~ "E. Europe High Oil",
     Oil == 0 & lamerica == 1 ~ "Latin A. Low Oil",
     Oil == 1 & lamerica == 1 ~ "Latin A. High Oil",
     Oil == 0 & asia == 1 ~ "Asia Low Oil",
     Oil == 1 & asia == 1 ~ "Asia High Oil",
     Oil == 0 & nafrme == 1 ~ "MENA Low Oil",
     Oil == 1 & nafrme == 1 ~ "MENA High Oil",
     Oil == 0 & ssafrica == 1 ~ "SS Africa Low Oil",
     Oil == 1 & ssafrica == 1 ~ "SS AFrica High Oil",
     Oil == 0 & western == 1 ~ "West/Japan Low Oil",
     Oil == 1 & western == 1 ~ "West/Japan High Oil",
    ))|>
  group_by(OilGeography)|>
  summarize(average_polity = mean(polity2, na.rm = TRUE))|>
  ggplot(mapping = aes(y = average_polity, x = OilGeography)) + geom_col(color = "blue") +
  theme(axis.text.x = element_text(angle = 90, size=8, vjust = 0.5, hjust=1)) + labs(y = "Average Polity Score", 
                                                                             x = "Region and Oil Dependency", title = "Average Polity Score Vs. Oil Revenue By Region", subtitle = "High Oil = Greater 1/3 Revenues From Fuel Exports")



plot1
    

```